version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: deployment
        image: thangved/anhphat-frontend
        ports:
            - 3000:3000
