version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: anhphat-frontend
        volumes:
            - ./build:/app/build
        ports:
            - 3000:3000
        command: ['npm', 'run', 'build']
